### ISSUE TITLE
nRF51822-Arduino doesn't support s120 or s130

### ISSUE THREAD

**Issue by joshuajnoble** [RedBearLab/nRF51822-Arduino#12]
Hi, s120 is already production ready and s130 is very close, it would be great if this library could support it :)

I'd be happy to help to try to support s120 if you could open up some of the toolchain.

**Comment by kteza1** [comment]
We need s120. Please support it.

**Comment by luposlip** [comment]
@joshuajnoble you've closed this - did you find a way around getting s120 and s130 to work?

**Comment by Cheong2K** [comment]
Hi @luposlip,

Use Keil and Nordic SDK to do that, after compiled a hex file, you can use drag and drop method to load to the BLE board.

**Comment by luposlip** [comment]
Thanks for the input @Cheong2K. Still looking forward to your support with Arduino SDK though! ;-)

**Comment by luposlip** [comment]
I see that Keil only works on Windows. Any alternatives for OSX?
