### ISSUE TITLE
nfr_sdk.a removed?

### ISSUE THREAD

**Issue by popsure** [RedBearLab/nRF51822-Arduino#14]
I was wondering why nfr_sdk.a has been removed from the repository, I'm using embedXcode and without this file I can't compile the library. Managed to find it in an older version:

https://github.com/RedBearLab/nRF51822-Arduino/blob/28d65df9ee7d652a8a70308929bd76f22173ac33/arduino-1.5.x/hardware/arduino/RBL_nRF51822/nrf51822_SDK/nrf_sdk.a?raw=true 

but I'm just curious why it's not in the current one anymore.

**Comment by Cheong2K** [comment]
We have made it as open source rather than just provide a static linked library. Please check.

**Comment by jrobeson** [comment]
probably can be closed now?

**Comment by popsure** [comment]
yes, this has been solved.

On 16 August 2015 at 11:48, Johnny Robeson <notifications@github.com> wrote:

> probably can be closed now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedBearLab/nRF51822-Arduino/issues/14#issuecomment-131515049>
> .
>



-- 



*POPSURE*Mick van Olst — Interactive Art Direction
mick@popsure.nl | www.popsure.nl | +49 152 021 98 352
