### ISSUE TITLE
Install the "Arduino SAM Boards" via Board Manager doesnt work

### ISSUE THREAD

**Issue by mg6074** [RedBearLab/nRF51822-Arduino#19]
Hello RedBearLab,

I am using BLE Nano with Arduino IDE 1.6.3. If I try to Install the "Arduino SAM Boards" add-on via Board Manager: Tools -> Board -> Board Manager. I get the error message "internet connection not available". But I have internet connection. Is there any solution forthis?

**Comment by Cheong2K** [comment]
Hi, I think it is better to ask Arduino team.

**Comment by luposlip** [comment]
It works fine for me, I suggest to close this issue.
