### ISSUE TITLE
Missing folders

### ISSUE THREAD

**Issue by BlueBeardo** [RedBearLab/nRF51822-Arduino#23]
I'm having a heck of time getting this branch to allow programs to be uploaded to the BLE Nano. Are you missing some folders? In the 1.5 version referenced on your main website I can get everything to upload and work just fine. With this I'm getting errors when I try to upload and a few errors about missing sections when I go into and out of board manager. 

Between this one and the 1.5 version folder set it looks like you are missing the folders:
-nrf51822_SDK
-system

And in the variants folder for the BLE_Nano you are missing:
-pins_arduino.h

Are these important. Should I just copy the files from the 1.5 version? I figured there was a newer set since the nrf51822_SDK folder also has the s110 and s120 folders. I figured there should be an s130 in this new set of folders.

**Comment by jrobeson** [comment]
seems to be there now.
