### ISSUE TITLE
update bundled SDK version?

### ISSUE THREAD

**Issue by jrobeson** [RedBearLab/nRF51822-Arduino#24]
I can't tell what version it is direclty, but seems like it's 6.x based on this post https://redbearlab.zendesk.com/entries/80681595-Helpful-things-for-working-with-nRF51-SDK-7-2-8-0

Is it possible to update it to sdk version 9?

**Comment by Cheong2K** [comment]
It does not rely on Nordic SDK, but it uses their SoftDevice S130 ver. 1.0 in the branch S130 repository.

**Comment by jrobeson** [comment]
ah. i thought there was more to it.
