### ISSUE TITLE
BLE_HRM compile error

### ISSUE THREAD

**Issue by desar** [RedBearLab/nRF51822-Arduino#3]
Follow the instruction on readme.md, but got the following error. Am I missing something?

C:\Users\devsar\AppData\Local\Temp\build8753222447677744552.tmp/syscalls.c.o: In function `_write':
C:\HOME\devtools\arduino\arduino-1.5.8\hardware\arduino\RBL_nRF51822\cores\arduino/syscalls.c:113: warning: undefined reference to`UART0_TX'

Thanks.

**Comment by jrobeson** [comment]
@Cheong2K : you can probably close this now.
