### ISSUE TITLE
RBL nRF51822 Firmware not working

### ISSUE THREAD

**Issue by sieren** [RedBearLab/nRF51822-Arduino#5]
Hey there,

I need to re-flash the MK20 Firmware onto the RBL_nRF51822 but it won't work.
Upon reboot I'm greeted with the constant flashing LED next t N0 and the mBED Drive won't show up.
The BOOTLOADER drive is also empty after rebooting the device and setting it back into BOOTLOADR mode.

Any idea what went wrong?

**Comment by luposlip** [comment]
Just for new comers: It works fine with the newest release of Yosemite (10.10.3+).
