### ISSUE TITLE
RBL 1.5 nano OTA not working, not showing up, not blinking

### ISSUE THREAD

**Issue by chrisallick** [RedBearLab/nRF51822-Arduino#52]
Hello,
I just received a BLE Nano Kit in the mail. I followed the instructions: added the board via Arduino, using 1.6.7, selected the 1.5 nano from the boards, uploaded blink, nothing happened.

The light on the bottom of the nano was flashing for a while, but now it has stopped. The nrf toolbox app does not show the nano.

What's going on? Seemingly totally broken.

**Comment by chrisallick** [comment]
Before it seemed to get through the "uploading" phase, now it simply just saying "Uploading..." forever.

**Comment by Cheong2K** [comment]
Hi,
It is about hardware issue, please write to:
support@redbearlab.com

**Comment by chrisallick** [comment]
The problem is that before anything will work with Arduino you MUST drag the new bootloader.hex file into the mBED drive. Then, after it reboots, the blink and BLEController sketch will work correctly.

I would highly recommend updating the "getting started." You've got a lot of conflicting information and it's split across multiple documents. Very frustrating.

**Comment by Cheong2K** [comment]
Didn't you read this? https://github.com/RedBearLab/nRF51822-Arduino/blob/S130/README.md
