### ISSUE TITLE
Rename Nordic S130 header back to ble.h (instead of nrf_ble.h)

### ISSUE THREAD

**Issue by sandeepmistry** [RedBearLab/nRF51822-Arduino#70]
Hi @zoujixing,

I've noticed the in the v1.0.6 release the S130 ble.h header was renamed to nrf_ble.h (https://github.com/RedBearLab/nRF51822-Arduino/commit/b18d721da79ed784f54dd8a64a5b693535555568). Do you know why this was done?

(This is the file in `arduino-1.6.x/hardware/RBL/RBL_nRF51822/cores/RBL_nRF51822/ble-nrf51822-master/source/nordic_sdk/components/softdevice/s130/headers/nrf_ble.h`).

It's causing some incompatibilities with my [arduino-BLEPeripheral library](https://github.com/sandeepmistry/arduino-BLEPeripheral) see https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/70 for more details. Can it be renamed back to `ble.h` in the v1.0.7 release?

cc/ @tigoe @szotyi007 @punamdahiya

**Comment by zoujixing** [comment]
Hi sandeepmistry,
    Thanks for your point.We will fix it in version1.0.7.

**Comment by tigoe** [comment]
Thanks, all, this will be a big help I imagine.

**Comment by sandeepmistry** [comment]
@zoujixing excellent, thank you for making this change! Looking forward to the v1.0.7 release.
