### ISSUE TITLE
package_redbearlab_index.json not parsing in arduino eclipse plugin

### ISSUE THREAD

**Issue by llemtt** [RedBearLab/nRF51822-Arduino#72]
I use the http://eclipse.baeyens.it/ eclipse plugin which does a stricter parsing on json files than Arduino IDE does and package_redbearlab_index.json doesn't work out of the box!

I had to had two matching brackets "packages":[ ... ] to let it parse correctly (see attachment).

[package_redbearlab_index.zip](https://github.com/RedBearLab/nRF51822-Arduino/files/410725/package_redbearlab_index.zip)

**Comment by zoujixing** [comment]
Thank you for point! We don't do a test on this eclipse plugin. We will fix this soon!
