### ISSUE TITLE
MBED driver is connected & disconnected continuously

### ISSUE THREAD

**Issue by venusyu0713** [RedBearLab/nRF51822-Arduino#88]
When RBL nRF51822 board connect with PC, MBED driver (E:\) is connected and disconnected continuously.
Power isn't off but BLE signal is off.

I tested it another PC but same problem occured.
Is it driver problem??

**Comment by zoujixing** [comment]
Try to update the interface firmware to DAPLink.
[https://github.com/RedBearLab/nRF51822-Arduino/tree/S130/interface/mk20/board_v1.0/daplink](url)

**Comment by venusyu0713** [comment]
How to update interface firmware??

**Comment by zoujixing** [comment]
Press button, then connect board to PC, you will see a driver "Bootloader".
Drag the bin file into the driver.
By the way, what is your PC system?

**Comment by venusyu0713** [comment]
Windows 10.

After update the interface firmware, my pc doesn't detect the driver(MBED).
Bootloader is detected when I plug board and then push the reset button.

**Comment by zoujixing** [comment]
what is your board version? 1.0?

**Comment by venusyu0713** [comment]
nRF51822 V1.5 (32KB)

**Comment by zoujixing** [comment]
Sorry, nRF51822 V1.5 can't use the new interface firmware, just use old [https://github.com/RedBearLab/nRF51822-Arduino/tree/S130/interface/mk20/board_v1.5/cmsis-dap](url)

Do you have other PC with window7 or linux? We meet this problem on window10, but it should work on other system.

**Comment by venusyu0713** [comment]
On Ubuntu system, It works. Thanks.

**Comment by tusharvb19** [comment]
using MK20 V1.0 but its not detecting in W10, ubuntu 16.04 after I upgrade the fw bootloader..I followed  steps
The MK20 is going into bootloader mode by pressing reset but it is not detecting as MBED or DAPLINK and led is off.
Need help.
