### ISSUE TITLE
no mass storage device comes up

### ISSUE THREAD

**Issue by ariesarditi** [RedBearLab/nRF51822-Arduino#9]
Hi,
When I plug in the board, no mass storage device named MBED comes up (initially it did, but not anymore).  The amber LED labeled L flashes fast.  I have followed the instructions for restoring the default MK20 firmware (successfully), but the MBED storage device no longer comes up. I am aware of the Yosemite read only issue and have used the suggested workaround.  I have also tried connecting the board to a windows machine -- still no MSD.

It would seem that the MK20 firmware you have in this repository is not up to date, or there is something wrong with my board.

Please advise.  Thanks.

**Comment by tusharvb19** [comment]
using MK20 V1.0 but its not detecting in W10, ubuntu 16.04 after I upgrade the fw bootloader..I followed steps
The MK20 is going into bootloader mode by pressing reset but it is not detecting as MBED or DAPLINK and led is off.
Need help.
